variables:
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.cache/npm"

cache:
  paths:
    - "$CI_PROJECT_DIR/.cache"

before_script:
  - echo "$NPMRC" >> .npmrc

types:
  - prepare
  - deploy

build:
  tags:
    - docker
  image: node:8.2
  type: prepare
  script:
    - npm install --quiet
    - npm run compile
  artifacts:
    paths:
      - node
      - module
      - types

test:
  tags:
    - docker
  image: node:8.2
  type: prepare
  script:
    - npm install --quiet
    - npm run lint
    - npm run coverage
  artifacts:
    paths:
      - report
  except:
    - tags

publish-module:
  tags:
    - docker
  image: node:8.2
  type: deploy
  script:
    - npm publish
  dependencies:
    - build
  only:
    - tags

